<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Himmelt.NFun</PackageId>
    <PackageVersion>1.2.2</PackageVersion>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2</AssemblyVersion>
    <FileVersion>1.2.2</FileVersion>
    <Title>NFun</Title>
    <Authors>Himmelt</Authors>
    <Company>Himmelt</Company>
    <Description>.NET 表达式求值器</Description>
    <Copyright>Copyright (c) 2025</Copyright>
    <PackageProjectUrl>https://github.com/Himmelt/NFun</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Himmelt/NFun.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>nuget_logo.png</PackageIcon>
    <PackageTags>expression-evaluator scripting type-inference optional-types named-types</PackageTags>
    <PackageReleaseNotes>扩展 WithFunction Delegate 方法；同步上游 NFun v1.2.2</PackageReleaseNotes>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NFun.nuspec" />
    <PackageReference Include="IndexRange" Version="1.0.2" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <None Update="Functions\GenericSwitchFunctionsGenerated.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>GenericSwitchFunctionsGenerated.cs</LastGenOutput>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\nuget_logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Functions\GenericSwitchFunctionsGenerated.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GenericSwitchFunctionsGenerated.tt</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
