<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>NFun.CompareToOthers</RootNamespace>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CoreCLR-NCalc" Version="2.2.88" />
        <PackageReference Include="IronPython" Version="2.7.11-candidate1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\NFun\NFun.csproj" />
    </ItemGroup>

</Project>
